name: qr_gen
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  gallery_saver: ^2.3.2
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  qr_flutter: ^4.0.0
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
